import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Analytics } from "@vercel/analytics/react"
import SplineScene from '@/components/animation'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  icons:'/logo.png',
  title: 'Lokesh Umredkar',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <Analytics/>

      </body>
    </html>
  )
}
